# encoding: UTF-8

FROM <%= ENV.fetch('FROM') %>:<%= ENV.fetch('TAG') %>
MAINTAINER The Blue Beluga <admin@bluebeluga.io>

LABEL vendor="The Blue Beluga Company"
LABEL io.bluebeluga.ruby.description="Ruby on Alpine Linux"
LABEL io.bluebeluga.ruby.version="<%= ENV.fetch('TAG') %>"
LABEL io.bluebeluga.ruby.git-revision="<%= ENV.fetch('GIT_REVISION') %>"
LABEL io.bluebeluga.ruby.release-date="<%= Time.now.strftime('%B %d, %Y %H:%M') %>"

RUN apk-install ruby ruby-irb ruby-bigdecimal ruby-io-console ruby-json \
                tzdata ca-certificates libssl1.0 openssl libstdc++

RUN { \
		echo 'install: --no-rdoc --no-ri'; \
		echo 'update: --no-rdoc --no-ri'; \
	  } >> /etc/gemrc \
 && gem install bundler

CMD [ "pry" ]
